### ISSUE TITLE
Unauthenticated error

### ISSUE THREAD

**Issue by cmargulhano** [FirebaseExtended/auth-without-play-services#1]
I implemented this solution, but after 1 hour (when the token expires) I can refresh token normally, but trying to save something in Firestore gives an unauthenticated error.

**Comment by samtstern** [comment]
@cmargulhano thanks for reporting!  That does sound like a bug in this solution.  Can you describe the steps to reproduce a little more?  Is it:

1. Open the app
2. Sign in
3. Perform some Firestore operation
4. Close the app.
5. Wait an hour
6. Try to perform another Firestore operation?

**Comment by cmargulhano** [comment]
It was really a problem in my implementation, as I was trying to put an observer in the background. I had to turn on the full Firestore logs to debug the problem. Everything really works. Thank you for your attention and share your knowledge, for our project was very valuable. Congratulations!!!

**Comment by samtstern** [comment]
@cmargulhano glad you got it working!
