### ISSUE TITLE
How to use it with Java code

### ISSUE THREAD

**Issue by ArcherEmiya05** [FirebaseExtended/auth-without-play-services#14]
Kotlin and Java are interoperable but I how can I use the FirebaseRestAuth class within a activity class that is written in Java while it is an interface class and not static singleton?

`auth = FirebaseRestAuth.getInstance(FirebaseApp.getInstance());` is what I think it should look when written in Java.

**Comment by ArcherEmiya05** [comment]
I discovered that it should be written as `auth = FirebaseRestAuth.Companion.getInstance(FirebaseApp.getInstance());`

**Comment by ElectricMagic** [comment]
> On 24 Sep 2020, at 13:27, ArcherEmiya <notifications@github.com> wrote:
> auth = FirebaseRestAuth.getInstance(FirebaseApp.getInstance()); is what it I think it should look when written in Java.

This is what I do:

public static FirebaseRestAuth sGetFirebaseRestAuth()
   { return (FirebaseRestAuth) FirebaseApp.getInstance().get(FirebaseRestAuth.class); }

A++
--- 
Andrew Green        skype:electricmagic       ag@em.net
Electric Magic Co.                    +1 (831) 621 1822

**Comment by ArcherEmiya05** [comment]
> 
> On 24 Sep 2020, at 13:27, ArcherEmiya ***@***.***> wrote: auth = FirebaseRestAuth.getInstance(FirebaseApp.getInstance()); is what it I think it should look when written in Java.
> This is what I do: public static FirebaseRestAuth sGetFirebaseRestAuth() { return (FirebaseRestAuth) FirebaseApp.getInstance().get(FirebaseRestAuth.class); } A++ --- Andrew Green skype:electricmagic ag@em.net Electric Magic Co. +1 (831) 621 1822

Is what I did wrong or just the same result as yours?

**Comment by ElectricMagic** [comment]
I had to go back and look to be sure!
My code's looking for the `FirebaseRestAuth` instance in the `FirebaseApp`'s pre-populated `ComponentRuntime`. So it should fail when `FirebaseRestAuth` has not been instantiated by the component registry mechanism. Going through `FirebaseRestAuth.Companion.getInstance`, we do always get a `FirebaseRestAuth`, but it's not necessarily `InternalAuthProvider` instance that the FirebaseApp itself would find.
This is really only an issue if the code is dynamically registering `FirebaseRestAuth` or `FirebaseAuth` at runtime, so you have `FirebaseRestAuth` code running, but a `FirebaseAuth` has been registered and is being used by other firebase components in preference to your `FirebaseRestAuth`.
