### ISSUE TITLE
Question about build.gradle files

### ISSUE THREAD

**Issue by ArcherEmiya05** [FirebaseExtended/auth-without-play-services#16]
I just wanted to ask what and why is `classpath 'com.google.gms:google-services:4.3.4'` along with `apply plugin: 'com.google.gms.google-services'` necessary? I knew that without this two there will be an error while building or running the app like calling Firebase instances. Can you please explain as why this two required aside that from being responsible on generating xml strings from google-services.json. Why this two works even without having Play Services in the device despite its name having `gms` on it.

**Comment by samtstern** [comment]
@ArcherEmiya05 good question!  The `google-services` plugin is poorly named, it has nothing to do with Google Play services.  So you can use it in your app without changing any runtime dependencies.

For some more information on how Firebase depends on Play services, see this page:
https://firebase.google.com/docs/android/android-play-services

**Comment by ArcherEmiya05** [comment]
> 
> 
> @ArcherEmiya05 good question! The `google-services` plugin is poorly named, it has nothing to do with Google Play services. So you can use it in your app without changing any runtime dependencies.
> 
> For some more information on how Firebase depends on Play services, see this page:
> https://firebase.google.com/docs/android/android-play-services

Thanks for noting that it was just poorly named and not really means it uses Play Services in any way, will bookmark this 
so I can point someone here as well for same question/concern.
