### ISSUE TITLE
Getting 403 error

### ISSUE THREAD

**Issue by troyhen** [FirebaseExtended/auth-without-play-services#2]
This was working for me a few months ago, but I tried it again and now I get a 403 error returned from the Firebase Auth REST service. Has anything changed recently that would cause this?

**Comment by samtstern** [comment]
@troyhen there haven't been any recent changes that I know of.  Mind sharing a little more about this error?  When does it happen, what's the URL, etc?

**Comment by troyhen** [comment]
Actually, I did find that there were changes to the REST service, documented here: https://firebase.google.com/docs/reference/rest/auth. I was able to get the code working again when I made changes to your code to adapt to this newer API. I also had to change where we get the Web API Key from. When you get it from the JSON file downloaded from the Firebase console, it did not match what you see visibly in the console, so I added a build config to always send the correct Web API Key. That was the main problem, and probably would have worked with your current version of this code. But you probably should update this to the newer API anyway. There were only a few changes.

**Comment by samtstern** [comment]
@troyhen interesting thanks for following up!  Could you describe the changes you had to make or maybe even send a Pull Request with your changes?

**Comment by troyhen** [comment]
I thought about that, but I had to convert your code to Kotlin and in putting it in our app, I changed the package structure somewhat. Over the weekend I can look at just my changes though, and see if I can't create a PR with similar changes to your code.

**Comment by troyhen** [comment]
Here's my PR https://github.com/FirebaseExtended/auth-without-play-services/pull/3

**Comment by samtstern** [comment]
Closing this issue because this workaround is no longer needed.  As of version 20.0.0 of the Firebase Auth SDK (released yesterday), we no longer require Google Play services 🎉 !

https://firebase.google.com/support/release-notes/android#auth_v20-0-0
