### ISSUE TITLE
Thoughts on turning this into an unofficial library?

### ISSUE THREAD

**Issue by SUPERCILEX** [FirebaseExtended/auth-without-play-services#4]
Hey Sam,
I don't have access to GMS at work, so I took inspiration from this repo and created [a Java version of the library](https://github.com/MasonAmerica/mason-check-in-kiosk/tree/38f587a26c59d58288ce53af9712436871a85452/auth/src/main/java/com/google/firebase/nongmsauth) that uses the GCP client SDKs so we don't have to do retrofit crap ourselves.

I think it'd be pretty cool to try and have a drop-in replacement for `FirebaseAuth` that people can pull in. Since I'd kinda be destroying the code already in this repo, I wanted to check with you first before trying to submit any PRs. Thoughts?

**Comment by SUPERCILEX** [comment]
cc @samtstern

**Comment by samtstern** [comment]
That sounds like the kind of thing you can/could/should do for the community ...  it's definitely not something I can do though. I don't want to step on the toes of the Firebase Auth team while they are actually working towards finding a permanent long-term solution for non-play devices.

Thanks for asking and show me what you have when you're done!

**Comment by SUPERCILEX** [comment]
> finding a permanent long-term solution for non-play devices

Ooooooh! As long as this is being worked on, I'm happy. :+1:

**Comment by samtstern** [comment]
@SUPERCILEX it's being worked on but not imminent, more of a medium-term project.
