### ISSUE TITLE
ComponentRegistrar not getting called

### ISSUE THREAD

**Issue by anotherdev** [FirebaseExtended/auth-without-play-services#7]
Hi @samtstern,

I successfully implemented Firebase Auth using REST api thanks to this repository and [the other one](https://github.com/MasonAmerica/mason-check-in-kiosk/blob/master/auth/src/main/java/com/google/firebase/nongmsauth/internal/FirebaseAuthCompatRegistrar.java) from @SUPERCILEX. I could login via anonymous, email, OAuth providers.

The problem is the `ComponentRegistrar` doesn't get called, so Firebase RTDB & Cloud Firestore doesn't know about the authentication. The merged manifest file does contain my code. Could you guys give me some pointers where the problem might be?

Merged manifest
```XML
<service
  android:name="com.google.firebase.components.ComponentDiscoveryService"
  android:directBootAware="true"
  android:exported="false" >
  <meta-data
    android:name="com.anotherdev.firebase.auth.rest.RestAuthComponentRegistrar"
    android:value="com.google.firebase.components.ComponentRegistrar" />
  <meta-data
    android:name="com.google.firebase.components:com.google.firebase.database.DatabaseRegistrar"
    android:value="com.google.firebase.components.ComponentRegistrar" />
</service>
```

ComponentRegistrar
```Java
public class RestAuthComponentRegistrar implements ComponentRegistrar {

    @Override
    public List<Component<?>> getComponents() {
        final Class<InternalAuthProvider> authProviderClass = InternalAuthProvider.class;
        final Class<FirebaseApp> firebaseAppClass = FirebaseApp.class;

        Component<InternalAuthProvider> component = Component.builder(authProviderClass)
                .add(Dependency.required(firebaseAppClass))
                .factory(container -> {
                    FirebaseApp app = container.get(firebaseAppClass);
                    return FirebaseAuthRest.getInstance(app);
                })
                .build();
        return Collections.singletonList(component);
    }
}
```

Thanks!
Polson

**Comment by samtstern** [comment]
@anotherdev thanks for filing this feedback, I don't actually know how to debug this.  Would you mind filing a new issue on the Firebase Android SDK repo and reference this one?  The component registry stuff is all part of the Core SDK so they should be able to help you figure out why it's not working.

**Comment by anotherdev** [comment]
Thanks for your reply! I found the cause through debugging. I have to prefix the name of my `ComponentRegistrar` with `com.google.firebase.components:`. So the result should be:

```java
com.google.firebase.components:<my fully qualified class name>
```

I'm curious to know, what drives the design to enforce using this prefix.
