### ISSUE TITLE
Potential API shutdown?

### ISSUE THREAD

**Issue by chrisfraser** [FirebaseExtended/auth-without-play-services#9]
Hi there guys,

I have just been looking at the reference docs and it looks like some of these APIS are shutting down. @samtstern can you please confirm the below?

<img width="938" alt="Screenshot 2020-05-06 at 20 39 32" src="https://user-images.githubusercontent.com/929529/81215785-2420e700-8fda-11ea-8c0e-94a72023250e.png">

https://developers.google.com/identity/toolkit

How does this impact the auth-without-play-services integration?

**Comment by samtstern** [comment]
@chrisfraser thanks for flagging this!  That note should probably be clearer. The identitytoolkit REST APIs will not be shut down as part of this.  This shutdown only affects the Google Identity Toolkit product which was sort of a precursor to FirebaseUI.

**Comment by chrisfraser** [comment]
Thanks Sam. I thought as much, but good to get some clarification.
